#!/bin/bash

echo "🎨 PDF Portfolio Generator - Quick Setup"
echo "======================================"
echo ""
echo "1. Install dependencies:"
echo "   npm install"
echo ""
echo "2. Create your portfolio structure:"
echo "   portfolio/"
echo "   ├── config.json"
echo "   ├── project1/"
echo "   │   ├── project.json"
echo "   │   ├── image1.jpg"
echo "   │   └── image2.jpg"
echo "   └── project2/"
echo "       ├── project.json"
echo "       └── cover.png"
echo ""
echo "3. Generate your portfolio:"
echo "   npm start -- --input ./portfolio --output my-portfolio.pdf"
echo ""
echo "4. Examples are available in the ./examples directory"
echo ""
echo "For more information, see the README.md file."
